### ISSUE TITLE
Add quantum composer calibration info into data files

### ISSUE THREAD

**Issue by stillwer** [NCAR/WVD-MCSupdate#149] opened 2018-04-30 16:03 UTC
The quantum composer is the master clock for the system. As such, it sets the pulse repetition frequency, the switching ratio, and the blank range. These are all useful calibration points and should be added to the data files that DIAL writes.

**Comment by BradSchoenrock** [comment] 2018-04-30 17:53
duplicate of #21, adding comment to that issue.

**Closed by BradSchoenrock** 2018-04-30 17:53 UTC
Labels: Duplicate, Enhancement
