### ISSUE TITLE
Children - error recovery

### ISSUE THREAD

**Issue by BradSchoenrock** [NCAR/WVD-MCSupdate#113] opened 2018-03-08 00:22 UTC
We want known errors to be able to recover. 

One example of this is the MCS UDP port becoming non responsive. We want the MCS to re-enter the config/init phases to reset the state of the MCS when the MCS regains UDP connectivity. Similar error handling needs to take place in other children.

**Comment by stillwer** [comment] 2018-05-24 23:29
Just got error warning -1073807265 from the Thor8000 box. It is caused by the modules in that box turning off. Scott thinks it is related to power spikes. Resolution is to program a warmup function that will turn all those things back on as needed.

**Comment by stillwer** [comment] 2018-05-24 23:29
Saw error 62 from the wave meter a few days ago. This error has not recurred but a trap can be added if it does. It is similar to error 66 and should be handled accordingly.

**Comment by stillwer** [comment] 2018-08-21 18:00
This is a very general comment. Individual errors are going to be logged here in the future so I am closing this issue.

**Closed by stillwer** 2018-08-21 18:00 UTC
Labels: Fault Tolerance
